input1 = open("marketopen.txt", "w")
input1.write("")
input1.close()
input2 = open("marketclose.txt", "w")
input2.write("")
input2.close()
input3 = open("tickers.txt", "w")
input3.write("")
input3.close()
